// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxS3Mrn0WxsCvu1y3kotLR77IPmyBbZzM',
    appId: '1:783828060486:web:fa60692ff3fdc63ec1fd47',
    messagingSenderId: '783828060486',
    projectId: 'note-it-3b607',
    authDomain: 'note-it-3b607.firebaseapp.com',
    storageBucket: 'note-it-3b607.appspot.com',
    measurementId: 'G-LG9T05S2WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6n8pMbJxyvVPAMTQU_S6Ir1QsIBlkQRI',
    appId: '1:783828060486:android:c7fa9b41f1a148f6c1fd47',
    messagingSenderId: '783828060486',
    projectId: 'note-it-3b607',
    storageBucket: 'note-it-3b607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChn3eqvNYIBSB10qKTRCpCbZAyJRxqUX8',
    appId: '1:783828060486:ios:99d4b7ea21390f26c1fd47',
    messagingSenderId: '783828060486',
    projectId: 'note-it-3b607',
    storageBucket: 'note-it-3b607.appspot.com',
    iosBundleId: 'com.example.noteAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChn3eqvNYIBSB10qKTRCpCbZAyJRxqUX8',
    appId: '1:783828060486:ios:99d4b7ea21390f26c1fd47',
    messagingSenderId: '783828060486',
    projectId: 'note-it-3b607',
    storageBucket: 'note-it-3b607.appspot.com',
    iosBundleId: 'com.example.noteAppMobile',
  );
}
